### ISSUE TITLE
authCallback not working with loginRedirect

### ISSUE THREAD

**Issue by buimanhhungit** [milestonetg/msal-js-dart#12]
AuthCallback not working with loginRedirect and loginpopup worked in the product.

<a href="https://ibb.co/MspK19p"><img src="https://i.ibb.co/NspfN7p/Screen-Shot-2020-08-23-at-08-28-02.png" alt="Screen-Shot-2020-08-23-at-08-28-02" border="0"></a>

<a href="https://imgbb.com/"><img src="https://i.ibb.co/NnXDX32/Screen-Shot-2020-08-23-at-08-34-16.png" alt="Screen-Shot-2020-08-23-at-08-34-16" border="0"></a>

**Comment by Francessco121** [comment]
Are you using Flutter?

msal.js has problem with Flutter where it can't get the redirect data after login from the URL because Flutter's router clears it before it gets the chance to read it. The only workaround I've found so far, is to call `handleRedirectCallback` before `runApp`.

**Comment by Francessco121** [comment]
Going to close this for now. Feel free to re-open with more details if you're still having trouble.
