### ISSUE TITLE
Not getting account information after successfull login

### ISSUE THREAD

**Issue by asifsaifi92** [milestonetg/msal-js-dart#20]
**Describe the bug**
I am using this package and after successfully login i am redirecting to my redirectURl page but i am not getting into the popup function callback and not getting the user account information

**To reproduce**
1.  Try to Login 
2. After login redirect url is coming which is fine 
3. But not getting user account information.

**Expected behavior**
Should return user account information

**Screenshots**
[If applicable, add screenshots to help explain your problem.](url)

**Environment (please complete the following information):**
 - Flutter: yes 
 - Browser: chrome
 - Dart msal_js Version: ^1.3.0
 - JavaScript msal.js Version: 1.1.3

I want to get user account information

**Comment by Francessco121** [comment]
The redirect login and popup login are two separate flows. After a redirect login, the redirect callback will be invoked (assuming you registered it with `handleRedirectCallback`) with token and account information. You can also get account information after a redirect or popup login using `getAccount`.

I'm a little confused as there is no "popup callback".

**Comment by asifsaifi92** [comment]
> The redirect login and popup login are two separate flows. After a redirect login, the redirect callback will be invoked (assuming you registered it with `handleRedirectCallback`) with token and account information. You can also get account information after a redirect or popup login using `getAccount`.
> 
> I'm a little confused as there is no "popup callback".

`void main() {
  // Create an MSAL logger
  final logger = Logger(
    _loggerCallback,
    LoggerOptions()
    // Log everything for the purpose of this demo
      ..level = LogLevel.verbose,
  );

  // Create an MSAL UserAgentApplication
  final userAgentApplication = UserAgentApplication(
    Configuration()
      ..auth = (AuthOptions()
        ..clientId = clientId
        ..authority = authority
      ..redirectUri = redirectUri

      )

      ..system = (SystemOptions()..logger = logger),
  );

  // Setup a callback for the redirect login flow
  //
  // **IMPORTANT NOTE:** It is highly recommended to setup
  // your UserAgentApplication and call handleRedirectCallback
  // sometime before your Flutter app starts. The router in
  // the [MaterialApp] widget will clear the URL when it loads
  // which will prevent MSAL from getting the token from it
  // after a redirect login.
  userAgentApplication.handleRedirectCallback(_redirectCallback);

  // Start the Flutter app
  runApp(MyApp(userAgentApplication: userAgentApplication));
}

void _loggerCallback(LogLevel level, String message, bool containsPii) {
  // MSAL log message
  print('MSAL: [$level] $message');
}

void _redirectCallback(AuthException error, [AuthResponse response]) {
  if (error != null) {
    // Redirect login failed
    print('MSAL: ${error.errorCode}:${error.errorMessage}');
  } else {
    // Redirect login succeeded
    print('Redirect login successful. name: ${response.account.name}');
  }
}

/// Simple default Flutter app.
///
/// Passes the [UserAgentApplication] onto the home page.
class MyApp extends StatelessWidget {
  final UserAgentApplication userAgentApplication;

  MyApp({@required this.userAgentApplication});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Web MSAL.js Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(userAgentApplication: userAgentApplication),
    );
  }
}

/// The demo home page for interacting with the
/// MSAL [UserAgentApplication].
class MyHomePage extends StatefulWidget {
  final UserAgentApplication userAgentApplication;

  MyHomePage({
    @required this.userAgentApplication,
    Key key,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Account _account;

  @override
  void initState() {
    super.initState();

    // Get the currently authenticated account, if any.
    //
    // After a redirect login, this returns the logged in account.
    _account = widget.userAgentApplication.getAccount();
  }

  /// Starts a redirect login.
  void _loginRedirect() {
    widget.userAgentApplication.loginRedirect(AuthRequest()..scopes = scopes);
  }

  /// Starts a popup login.
  Future<void> _loginPopup() async {
    try {
      final response = await widget.userAgentApplication
          .loginPopup(AuthRequest()..scopes = scopes);

      setState(() {
        _account = response.account;
      });
var acces_token = response.accessToken;
      print('Popup login successful. name: ${response.account.name}');
    } on AuthException catch (ex) {
      print('MSAL: ${ex.errorCode}:${ex.errorMessage}');
    }
    print("");
  }

  /// Logs the current account out.
  ///
  void _logout() {
    widget.userAgentApplication.logout();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Web MSAL.js Demo'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            if (_account == null) ...[
              RaisedButton(
                child: Text('Login Redirect'),
                onPressed: _loginRedirect,
              ),
              RaisedButton(
                child: Text('Login Popup'),
                onPressed: _loginPopup,
              ),
            ],
            if (_account != null) ...[
              Text('Signed in as ${_account.name}'),
              RaisedButton(
                child: Text('Logout'),
                onPressed: _logout,
              ),
            ]
          ],
        ),
      ),
    );
  }
}`

here is my main.dart code . Can you please explain where will i get user account information?

**Comment by asifsaifi92** [comment]
> The redirect login and popup login are two separate flows. After a redirect login, the redirect callback will be invoked (assuming you registered it with `handleRedirectCallback`) with token and account information. You can also get account information after a redirect or popup login using `getAccount`.
> 
> I'm a little confused as there is no "popup callback".

I am not getting user account info in this function after successfully logged in
// Starts a popup login.
Future _loginPopup() async {
try {
final response = await widget.userAgentApplication
.loginPopup(AuthRequest()..scopes = scopes);

  setState(() {
    _account = response.account;
  });
var acces_token = response.accessToken;
print('Popup login successful. name: ${response.account.name}');
} on AuthException catch (ex) {
print('MSAL: ${ex.errorCode}:${ex.errorMessage}');
}
print("");
}

**Comment by Francessco121** [comment]
Are you initiating a popup login or a redirect login? I also noticed that you are using msal.js 1.1, you should consider upgrading to 1.4 to make sure this isn't a weird msal.js bug.

Also, does the Flutter example work without changes to it?

**Comment by asifsaifi92** [comment]
> Are you initiating a popup login or a redirect login? I also noticed that you are using msal.js 1.1, you should consider upgrading to 1.4 to make sure this isn't a weird msal.js bug.
> 
> Also, does the Flutter example work without changes to it?

I am using pop login . So now i have changed msal.js 1.4.4 . My index.html file is 
`<script type="text/javascript" src="https://alcdn.msauth.net/lib/1.4.4/js/msal.min.js"></script>
  <script type="text/javascript" src="https://alcdn.msauth.net/lib/1.4.4/js/msal.js" integrity="sha384-3cT22wEPS/umVHpe5hGwbRF8PLObcSXaaFncKfbzutTBzn/aEMQ6aIlxaa6J2TG1" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://alcdn.msauth.net/lib/1.4.4/js/msal.min.js" integrity="sha384-kYijiCrNWywvKX1VI7259ktIf0ebXhlDeVD2dBEX+GeVbmY1GEboq3dsDDvYuDP/" crossorigin="anonymous"></script>


  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js" class="pre"></script>
  <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.4.4/js/msal.min.js"></script>
  <script src="main.dart.js" type="application/javascript"></script>`

**Comment by Francessco121** [comment]
This looks like you're loading msal.js 4 times? That might be causing an issue.

**Comment by asifsaifi92** [comment]
> This looks like you're loading msal.js 4 times? That might be causing an issue.

okay , i have corrected index.html now 
`<script type="text/javascript" src="https://alcdn.msauth.net/lib/1.4.4/js/msal.min.js"></script>`

i am loading msal.js only once now. but problem is still same. Do you suggest me some working code sample?

**Comment by Francessco121** [comment]
Try the [Flutter example](https://github.com/milestonetg/msal-js-dart/blob/master/example/flutter_web_example.md) as is (just change the config to your stuff). I know that example works with at least msal.js 1.3 and should work perfect with 1.4.

If that doesn't work then it's either your config or possibly a new Flutter version breaking something. Unfortunately I do not use this package with Flutter myself so it's not super well tested there.

**Comment by Francessco121** [comment]
Closing for now, feel free to reply back here with more information if possible and I'd be happy to reopen this.

**Comment by hillelcoren** [comment]
I had the same problem but was able to resolve it by adding http://localhost:8080/ as a redirect URI in the Azure settings and in the code.
