### ISSUE TITLE
[Flutter web] Stuck at redirect uri page, unable to finish Login flow

### ISSUE THREAD

**Issue by KeeganDC** [milestonetg/msal-js-dart#38]
### Description

Apologies in advance, if this isn't a bug or I didn't setup correctly

I was able to setup, run and launch the B2C Login web page but unable to finish the flow

### Reproduction steps

1. Clone master branch 
2. Open https://github.com/Francessco121/msal-js-dart/tree/master/example/flutter_example as Flutter project
3. Make the code changes below
4. Launch Flutter web app onto Chrome successfully
5. Tap on "Login Redirect" or "Login Popup"
6. Load B2C page successfully
7. Enter email and password of a valid account
8. Redirect to expected redirect uri e.g. https://localhost:60200/#state=eyJpZCI6ImQ4OTM0YTEwLTE1ZjUtNGNmYS05ODA3LTU0NDYwNTU3YTIyMyIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0%3d&client_info=eyJ1aWQiOiJmZGU0[......]&code=eyJraWQiOiJoZ1V[......]
9. Stuck on this redirect uri page
10. Close pop up page
11. Log shows an error

Note: I redacted some of the configs with `[......]` and `redactedname`

Code changes from step 3 above:
``` 
// **Setup your directory settings here**:
const String clientId = 'e60e3041-a9ed-[.......]; // edited code
const String authority = 'https://redactedname.b2clogin.com/redactedname.onmicrosoft.com/B2C_1A_SIGNINSIGNUP'; // new code
const String redirectUri = 'https://localhost:60200'; // new code

const List<String> scopes = [
  'https://redactedname.onmicrosoft.com/api/items.read', // edited code
];
```

```
      ..auth = (BrowserAuthOptions()
        // Give MSAL our client ID
        ..clientId = clientId
        ..knownAuthorities = [authority] // new code
          ..authority = authority // new code
          ..redirectUri = redirectUri // new code
      )
```

```
  /// Starts a redirect login.
  void _loginRedirect() {
    widget.publicClientApp.loginRedirect(RedirectRequest()
      ..scopes = scopes
      ..authority = authority // new code
    );
```

```
  /// Starts a popup login.
  Future<void> _loginPopup() async {
    try {
      final response = await widget.publicClientApp.loginPopup(PopupRequest()
        ..scopes = scopes
        ..authority = authority // new code
     );
```

Full log:
```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:52803/yWTWXpnZnqU=/ws
Debug service listening on ws://127.0.0.1:52803/yWTWXpnZnqU=/ws
Debug service listening on ws://127.0.0.1:52803/yWTWXpnZnqU=/ws
MSAL: [LogLevel.info] [Fri, 16 Jun 2023 01:51:59 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectStart
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:51:59 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:51:59 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:51:59 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
MSAL: [LogLevel.info] [Fri, 16 Jun 2023 01:51:59 GMT] :  : @azure/msal-browser@2.14.2 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
MSAL: [LogLevel.info] [Fri, 16 Jun 2023 01:51:59 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectEnd
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:51:59 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:51:59 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getActiveAccount: No active account
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - loginPopup called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - preflightBrowserEnvironmentCheck started
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - acquireTokenPopup called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - preflightInteractiveRequest called, validating app environment
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeAuthorizationRequest called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getRedirectUri called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Initializing BaseAuthRequest
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getActiveAccount: No active account
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - asyncPopup set to false, opening popup before acquiring token
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - acquireTokenPopupAsync called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
MSAL: [LogLevel.info] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:loginStart
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createAuthCodeClient called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called
MSAL: [LogLevel.verbose] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority
MSAL: [LogLevel.info] [Fri, 16 Jun 2023 01:52:00 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:popupOpened
MSAL: [LogLevel.info] [Fri, 16 Jun 2023 01:52:17 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:loginFailure
Error: BrowserAuthError: user_cancelled: User cancelled the flow.


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 321:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 337:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1386:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15           <fn>
```

### Expected behavior

Expected result #1: B2C login page to close and finish Login successfully at Step 9

Expected result #2: Shoduln't throw an error at step 11 if user closes the pop up (same result if step 7 - 9 is skipped)
i.e.
>  Step 6. Load B2C page successfully
>  Step 10. Close pop up page
>  Step 11. Log shows an error

Should be returning and printing an `AuthException` error?
i.e.
```
 } on AuthException catch (ex) {
      print('MSAL: ${ex.errorCode}:${ex.errorMessage}');
```

### Using Flutter

Yes

### Browser

Chrome on MacOS

### Dart msal_js version

2.14.0

### JavaScript msal.js version

N/A for Flutter?

**Comment by Francessco121** [comment]
Hey there,

I just tried the Flutter example and both the popup and redirect flows work for me (msal.js 2.14.2, which is the same version you're using). Also I ran this test on Flutter 3.10.5, not sure if that matters.

Your configuration may be wrong. The fact that you got a `BrowserAuthError` at all is good though, that means that the login page did redirect and MSAL did pick up the token/info from the URL.

Regarding the exception not being caught, it seems that JS interop changed in Dart 3 and the error catching method used in this package no longer works. I'll need to spend more time looking into that. For now, assume that error handling in this package will only work on Dart 2.x.

Also, the msal.js version that comes with the Flutter example is a bit outdated now. If you get this working, I recommend upgrading to the latest 2.x version (just change the `<script>` tag in `index.html` or download the latest .js dist).

**Comment by Francessco121** [comment]
> do you want me to close this and create a separate issue for it?

That's alright, I just created a new issue for it (#39). You can close this if you've solved the configuration issue, otherwise please let me know if you run into any other problems.

I'll try to spend some time this weekend looking for a fix, it would be nice to publish a small patch for Dart 3 users.

**Comment by Francessco121** [comment]
Hmm... Have you tried upgrading the version of msal.js your application is using? There's a good chance this is just a bug in the underlying library (which historically has been very buggy over the years). The latest version that should work is `2.34.0`. Technically `2.37.0` exists but they never uploaded a CDN version of it for whatever reason, `2.36.0` doesn't seem to exist, and `2.35.0` has a pretty bad bug in it with ID tokens not getting captured, which certainly won't help you 🙂.

You can find the CDN URLs with their hashes here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/cdn-usage.md

Unfortunately, I'm not really sure that there's anything I can do. This Dart wrapper is very minimal and just forwards calls directly to the JS library, which I'm not a developer of. As far as I can tell from the information you've provided, the Dart side of things seem to be working just fine (aside from the exception handling, which isn't necessary for the happy path).

Worst case, I would open an issue in the MSAL repository. They obviously won't know what to do with your Dart code, but if you provide them your configuration and msal.js version, they should be able to help.

**Comment by Francessco121** [comment]
Oh, one other thing. There's a chance the documentation in this package is slightly out of date now. I tried mirroring the official docs the best I could, but it hasn't been updated in a while. I recommend taking a look at the official msal.js docs just to make sure there isn't some special case for your setup that's missing.

**Comment by Francessco121** [comment]
👍 If you run into any new issues, feel free to re-open this or make a new issue.
